In [2]:
from sklearn.datasets import load_iris
import numpy as np
from matplotlib import pyplot as plt

In [3]:
data =load_iris(return_X_y=False)


In [4]:
X = data.data
y = data.target

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =42) 

print(X_train.shape)
print(X_test)


(120, 4)
[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [6.9 3.1 5.1 2.3]
 [6.2 2.2 4.5 1.5]
 [5.8 2.7 3.9 1.2]
 [6.5 3.2 5.1 2. ]
 [4.8 3.  1.4 0.1]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.8 1.5 0.3]
 [6.3 3.3 4.7 1.6]
 [6.5 3.  5.8 2.2]
 [5.6 2.5 3.9 1.1]
 [5.7 2.8 4.5 1.3]
 [6.4 2.8 5.6 2.2]
 [4.7 3.2 1.6 0.2]
 [6.1 3.  4.9 1.8]
 [5.  3.4 1.6 0.4]
 [6.4 2.8 5.6 2.1]
 [7.9 3.8 6.4 2. ]
 [6.7 3.  5.2 2.3]
 [6.7 2.5 5.8 1.8]
 [6.8 3.2 5.9 2.3]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]]


In [6]:

from sklearn.naive_bayes import GaussianNB

modelo = GaussianNB()


In [7]:
#Búsqueda por rejilla
from sklearn.model_selection import GridSearchCV

rejilla = {'priors':[None,[0.25,0.5,0.25], [0.5,0.25,0.25],[0.25,0.25,0.5]]}

modeloGridSearchCrossValidation = GridSearchCV(estimator=modelo,param_grid=rejilla,scoring='accuracy',cv=10)

modeloGridSearchCrossValidation.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'priors': [None, [0.25, 0.5, 0.25], [0.5, 0.25, 0.25],
                                    [0.25, 0.25, 0.5]]},
             scoring='accuracy')

In [8]:
#Resultados
modeloGridSearchCrossValidation.cv_results_


{'mean_fit_time': array([0.00126879, 0.00153017, 0.00174685, 0.00100536]),
 'std_fit_time': array([0.0006489 , 0.00073126, 0.0008194 , 0.00046258]),
 'mean_score_time': array([0.00129304, 0.00132115, 0.00444205, 0.00097709]),
 'std_score_time': array([0.0005332 , 0.00048544, 0.00850528, 0.00054477]),
 'param_priors': masked_array(data=[None, list([0.25, 0.5, 0.25]), list([0.5, 0.25, 0.25]),
                    list([0.25, 0.25, 0.5])],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'priors': None},
  {'priors': [0.25, 0.5, 0.25]},
  {'priors': [0.5, 0.25, 0.25]},
  {'priors': [0.25, 0.25, 0.5]}],
 'split0_test_score': array([0.91666667, 0.91666667, 0.91666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([1., 1., 1., 1.]),
 'split3_test_score': array([1., 1., 1., 1.]),
 'split4_test_score': array([0.75, 0.75, 0.75, 0.75]),
 'split5_test_score': array([0.91666667, 1.  

In [9]:
#Best score:
modeloGridSearchCrossValidation.best_score_

np.float64(0.9583333333333333)

In [10]:
mejorModelo = modeloGridSearchCrossValidation.best_estimator_
mejorModelo.fit(X_train,y_train)

GaussianNB(priors=[0.25, 0.5, 0.25])

In [11]:
y_pred = mejorModelo.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_pred,y_test)

1.0

In [13]:
#Ver los parámetros ajustados
mejorModelo.theta_

array([[4.99      , 3.4525    , 1.45      , 0.245     ],
       [5.9195122 , 2.77073171, 4.24146341, 1.32195122],
       [6.53333333, 2.96666667, 5.52051282, 2.        ]])

In [ ]:
#Varianzas
mejorModelo.var_

array([[0.1239    , 0.15249375, 0.033     , 0.010975  ],
       [0.28693635, 0.10011898, 0.22584176, 0.04122546],
       [0.4165812 , 0.0991453 , 0.28573307, 0.08205129]])